// api.js
export const API_URL = 'http://127.0.0.1:8000/api'; 
// export const API_URL = 'https://dbsf.friendz.id/api'; 
export const URL_BASE = 'http://127.0.0.1:8000'; 

export const ENDPOINTS = {
  USER: '/user',
  LOGIN_STAFF: '/auth/loginStaff',
  LOGOUT: '/acc/logout',
  REGISTER_STAFF: '/regs/registerStaff',
  ROLEGET: '/roles',
  ROLESTO: '/roles',
  TEPDELETE: '/roles/dest/{id}',
  TEPPUT: '/roles/{id}',
  ME: '/acc/me',
  PROFGET: '/profile',
  PROFSTO: '/profile',
  RKPAGT: '/rekap/anggota',
  ALLAJEN: '/schdl',
  ALLUSER: '/acc/all',
  ALLUSERS: '/acc/alls',
  ASAL: '/task',
};
// export const ENDPOINTS = {
//   USER: '/user',
//   VERMEL: '/reverified',
//   FORPW: '/password/email',
//   SETPW: '/password/reset',
//   PIPELDTL: '/det/stafdth',
//   CRETDTL: '/det/detStaff/{id}',
//   KLINDET: '/det/usrdtl',
//   SELFDET: '/det/stafdtlcom',
//   SELFPP: '/det/serpp',
//   USERDTLALL: '/det/gtdt',
//   USERALL: '/wong/gtusr',
//   CHPW: '/wong/chpwe/{id}',
//   ALLUSER: '/rekp/userlis',
//   REGISTER_STAFF: '/regs/registerStaff',
//   REGISTER_USER: '/regs/registerUser',
//   LOGIN_STAFF: '/nope/loginStaff',
//   LOGINN: '/acac/login',
//   LOGIN_USER: '/nope/loginUser',
//   ME: '/acc/me',
//   REFRESH: '/acc/refresh',
//   LOGOUT: '/acc/logout',
//   ALLUS: '/wong/usrall',
//   ALUS: '/wong/gtusr',
//   CHAPROF: '/wong/chprof/{id}',
//   CHAPROFF: '/wong/chproff/{id}',
//   CHAPW: '/wong/chpwe/{id}',
//   DETSTAF: '/det/detStaff/{id}',
//   DETUSE: '/det/detUser/{id}',
//   GETAU: '/det/gtdt',
//   TEPGET: '/tep/usty',
//   TEPPOST: '/tep/cretep',
//   TEPPUT: '/tep/aptep/{id}',
//   TEPDELETE: '/tep/deltep/{id}',
//   GTSERVICE: '/serp/allser',
//   PSCRETSERV: '/serp/creser',
//   PSEDTSERV: '/serp/aptser/{id}',
//   DELSERV: '/serp/delser/{id}',
//   GTIZ: '/izz/allizn',
//   GTIZID: '/izz/alliznid/{id}',
//   CREIZ: '/izz/ezen/{id}',
//   UPIZ: '/izz/upizn/{id}',
//   UPIZID: '/izz/upiznadm/{id}',
//   DELIZ: '/izz/delizn/{id}',
//   ASAL: '/assign/all',
//   ASGE: '/assign/getfor/{id}',
//   ASCRE: '/assign/create/{id}',
//   ASDET: '/assign/update/{id}',
//   ASDETST: '/assign/updatest/{id}',
//   ASLET: '/assign/delete/{id}',
//   PRESLOG: '/presensi/create/{id}',
//   PRESOUT: '/presensi/update/{id}',
//   GETPRESALL: '/presensi/getall',
//   GETPRESUSER: '/presensi/getuser',
//   ANALYS: '/rekp/rekap',
//   TUDU: '/rekp/asmn',
//   AGEND: '/rekp/upcom',
//   REK: '/rek/all',
//   REKCRET: '/rek/create',
//   REKUPDT: '/rek/update/{id}',
//   REKDEL: '/rek/delete/{id}',
//   ALLAJEN: '/ajend/allgen',
//   ALLAJBYID: '/ajend/gegen/{id}',
//   NEWAJEN: '/ajend/cretagen/{id}',
//   UPAJEN: '/ajend/apgen/{id}',
//   DELJEN: '/ajend/delgen/{id}',
//   PAYALL: '/paym/all',
//   ORDALL: '/ord/showall',
//   ORDALLST: '/odr/tahu/{id}',
//   ORDDTL: '/odr/getz',
//   INP: '/inp/inponya',
//   INPN: '/inp/new',
//   INPU: '/inp/chinp/{id}',
//   INPD: '/inp/delinp/{id}',
//   REI: '/rei/allrei',
//   REIBYID: '/rei/alliznid/{id}',
//   REIC: '/rei/cret/{id}',
//   REIU: '/rei/upd/{id}',
//   REIUA: '/rei/updadm/{id}',
//   REID: '/rei/del/{id}',
//   ORDRH: '/ord/updt/{id}',
//   RKPPRES: '/rekap/rek-presen',
//   RKPPRESME: '/rekap/rek-presen-me',
//   RKPAGT: '/rekap/anggota',
//   RKPAGTDTL: '/rekap/anggota-detail',
//   // JENBYID: '/ajend/gegen/{id}',
// };
